#pragma config(Sensor, dgtl2,  button1,        sensorTouch)
#pragma config(Sensor, dgtl3,  button2,        sensorTouch)
#pragma config(Sensor, dgtl9,  sensorOutput,   sensorDigitalOut)
#pragma config(Sensor, dgtl10, sensorInput,    sensorDigitalIn)
#pragma config(Sensor, dgtl11, leftBumper,     sensorTouch)
#pragma config(Sensor, dgtl12, rightBumper,    sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          armMotor,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool button1_pushed; //flag to store button1 input
bool button2_pushed; //flag to store button2 input
bool rightBumper_pushed;

#define TASK_NUMBER 2

void monitorInput()
{
	if(SensorValue(button1) && !button1_pushed)
	{
		button1_pushed = true;
	}
	if(SensorValue(button2) & !button2_pushed)
    {
        button2_pushed = true;
    }
	if(SensorValue(rightBumper) & !rightBumper_pushed)
    {
        rightBumper_pushed = true;
    }
}

void task_1()
{

	while(true)
	{
		monitorInput();
		if( button1_pushed ) {


			motor[rightMotor] = 40;
			motor[leftMotor] = 57;
			button1_pushed = false;
			wait10Msec(220);
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;

		}

		if(button2_pushed){

			motor[rightMotor] = 45;
			motor[leftMotor] = -50;
			button2_pushed = false;
			wait10Msec(42);
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;


		}
	}
}

void task_2()
{

while(true)
	{
		monitorInput();
		if( button1_pushed) {


		/*	motor[rightMotor] = 30;
			motor[leftMotor] = 40;
			button1_pushed = false;
			wait10Msec(300);
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;*/
			motor[armMotor] = -20;
			wait10Msec(100);
			motor[armMotor] = 0;
			wait10Msec(50);
			motor[armMotor] = 25;
			wait10Msec(100);
			motor[armMotor] = 0;
			motor[rightMotor] = -20;
			motor[leftMotor] = -20;
			motor[armMotor] = -30;
			wait10Msec(50);
			motor[armMotor] = 0;
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;
			button1_pushed = false;
		}
		if(button2_pushed){
			motor[armMotor] = 20;
			wait10Msec(1);
			motor[armMotor] = 0;
			button2_pushed = false;

		}
	if (rightBumper_pushed){
			motor[armMotor] = -20;
			wait10Msec(1);
			motor[armMotor] = 0;
			rightBumper_pushed = false;
		}

}
		}
void test_2()
{

while(true)
	{
		monitorInput();
		if( button1_pushed ) {
			motor[armMotor] = -20;
			wait10Msec(100);
			motor[armMotor] = 0;
			wait10Msec(50);
			motor[armMotor] = 25;
			wait10Msec(100);
			motor[armMotor] = 0;
			button1_pushed = false;

		}
		if(button2_pushed){
			motor[armMotor] = 20;
			wait10Msec(1);
			motor[armMotor] = 0;
			button2_pushed = false;
		}
	}
}

task main()
{
	switch (TASK_NUMBER)
	{
case 1:
		task_1();
		break;
case 2:
		task_2();
		break;
case 3:
		test_2();
		break;
}
}
